// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3fKpw31mJEyjBZw1KGMBsJQf9H_Nogao',
    appId: '1:294326491041:web:771e7d940416ac39431de0',
    messagingSenderId: '294326491041',
    projectId: 'farmsenseai-68987',
    authDomain: 'farmsenseai-68987.firebaseapp.com',
    storageBucket: 'farmsenseai-68987.firebasestorage.app',
    measurementId: 'G-W7QCFDD3LF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFdBQxK0aOYnXoA8-gwpI-9qvMtPe27Ik',
    appId: '1:294326491041:android:4fad3e9b3b0f72d5431de0',
    messagingSenderId: '294326491041',
    projectId: 'farmsenseai-68987',
    storageBucket: 'farmsenseai-68987.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3fKpw31mJEyjBZw1KGMBsJQf9H_Nogao',
    appId: '1:294326491041:web:f6659fba4f2c7d0d431de0',
    messagingSenderId: '294326491041',
    projectId: 'farmsenseai-68987',
    authDomain: 'farmsenseai-68987.firebaseapp.com',
    storageBucket: 'farmsenseai-68987.firebasestorage.app',
    measurementId: 'G-9SF7KY14YZ',
  );
}
